Martynas K: Fix Centos8 AppStream repository issues.
The AppStream repository must be switched to "vault".
Otherwise smth. like this will be encountered
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Original AppStream would be pointing to Centos Stream repo otherwise.